package com.stuidentity.web.mybatis.domain;

import java.util.Date;

public class Creditscore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditscore.id
     *
     * @mbggenerated
     */
    private String id;

    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditscore.userid
     *
     * @mbggenerated
     */
    private String stuidcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditscore.creditscoretotal
     *
     * @mbggenerated
     */
    private Double creditscoretotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditscore.identityscore
     *
     * @mbggenerated
     */
    private Double identityscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditscore.performscore
     *
     * @mbggenerated
     */
    private Double performscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditscore.historyscore
     *
     * @mbggenerated
     */
    private Double historyscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditscore.peoplekeepscore
     *
     * @mbggenerated
     */
    private Double peoplekeepscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditscore.behaviorscore
     *
     * @mbggenerated
     */
    private Double behaviorscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditscore.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditscore.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditscore
     *
     * @mbggenerated
     */
    public Creditscore(String id, String userid, String stuidcard, Double creditscoretotal, Double identityscore, Double performscore, Double historyscore, Double peoplekeepscore, Double behaviorscore, Date createdate, String remark) {
        this.id = id;
        this.userid = userid;
        this.stuidcard = stuidcard;
        this.creditscoretotal = creditscoretotal;
        this.identityscore = identityscore;
        this.performscore = performscore;
        this.historyscore = historyscore;
        this.peoplekeepscore = peoplekeepscore;
        this.behaviorscore = behaviorscore;
        this.createdate = createdate;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditscore
     *
     * @mbggenerated
     */
    public Creditscore() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditscore.id
     *
     * @return the value of creditscore.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditscore.id
     *
     * @param id the value for creditscore.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getStuidcard() {
        return stuidcard;
    }

    public void setStuidcard(String stuidcard) {
        this.stuidcard = stuidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditscore.creditscoretotal
     *
     * @return the value of creditscore.creditscoretotal
     *
     * @mbggenerated
     */
    public Double getCreditscoretotal() {
        return creditscoretotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditscore.creditscoretotal
     *
     * @param creditscoretotal the value for creditscore.creditscoretotal
     *
     * @mbggenerated
     */
    public void setCreditscoretotal(Double creditscoretotal) {
        this.creditscoretotal = creditscoretotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditscore.identityscore
     *
     * @return the value of creditscore.identityscore
     *
     * @mbggenerated
     */
    public Double getIdentityscore() {
        return identityscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditscore.identityscore
     *
     * @param identityscore the value for creditscore.identityscore
     *
     * @mbggenerated
     */
    public void setIdentityscore(Double identityscore) {
        this.identityscore = identityscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditscore.performscore
     *
     * @return the value of creditscore.performscore
     *
     * @mbggenerated
     */
    public Double getPerformscore() {
        return performscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditscore.performscore
     *
     * @param performscore the value for creditscore.performscore
     *
     * @mbggenerated
     */
    public void setPerformscore(Double performscore) {
        this.performscore = performscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditscore.historyscore
     *
     * @return the value of creditscore.historyscore
     *
     * @mbggenerated
     */
    public Double getHistoryscore() {
        return historyscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditscore.historyscore
     *
     * @param historyscore the value for creditscore.historyscore
     *
     * @mbggenerated
     */
    public void setHistoryscore(Double historyscore) {
        this.historyscore = historyscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditscore.peoplekeepscore
     *
     * @return the value of creditscore.peoplekeepscore
     *
     * @mbggenerated
     */
    public Double getPeoplekeepscore() {
        return peoplekeepscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditscore.peoplekeepscore
     *
     * @param peoplekeepscore the value for creditscore.peoplekeepscore
     *
     * @mbggenerated
     */
    public void setPeoplekeepscore(Double peoplekeepscore) {
        this.peoplekeepscore = peoplekeepscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditscore.behaviorscore
     *
     * @return the value of creditscore.behaviorscore
     *
     * @mbggenerated
     */
    public Double getBehaviorscore() {
        return behaviorscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditscore.behaviorscore
     *
     * @param behaviorscore the value for creditscore.behaviorscore
     *
     * @mbggenerated
     */
    public void setBehaviorscore(Double behaviorscore) {
        this.behaviorscore = behaviorscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditscore.createdate
     *
     * @return the value of creditscore.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditscore.createdate
     *
     * @param createdate the value for creditscore.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditscore.remark
     *
     * @return the value of creditscore.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditscore.remark
     *
     * @param remark the value for creditscore.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}