package com.stuidentity.web.mybatis.domain;

import java.util.Date;

public class Studentroll {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.id
     *
     * @mbggenerated
     */
    private String id;

    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.stuname
     *
     * @mbggenerated
     */
    private String stuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.stusex
     *
     * @mbggenerated
     */
    private String stusex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.stuidcard
     *
     * @mbggenerated
     */
    private String stuidcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.school
     *
     * @mbggenerated
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.edulevel
     *
     * @mbggenerated
     */
    private String edulevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.major
     *
     * @mbggenerated
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.edusystem
     *
     * @mbggenerated
     */
    private String edusystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.edutype
     *
     * @mbggenerated
     */
    private String edutype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.edumode
     *
     * @mbggenerated
     */
    private String edumode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.branch
     *
     * @mbggenerated
     */
    private String branch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.class
     *
     * @mbggenerated
     */
    private String classgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.stunum
     *
     * @mbggenerated
     */
    private String stunum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.admissiondate
     *
     * @mbggenerated
     */
    private Date admissiondate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.leavedate
     *
     * @mbggenerated
     */
    private Date leavedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.stustate
     *
     * @mbggenerated
     */
    private String stustate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentroll.remark
     *
     * @mbggenerated
     */
    private String remark;

    private String isstuidentity;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentroll
     *
     * @mbggenerated
     */
    public Studentroll(String id, String userid, String stuname, String stusex, String stuidcard, String school
            , String edulevel, String major, String edusystem, String edutype, String edumode, String branch
            , String classgrade, String stunum, Date admissiondate, Date leavedate, String stustate
            , String remark, String isstuidentity) {
        this.id = id;
        this.userid = userid;
        this.stuname = stuname;
        this.stusex = stusex;
        this.stuidcard = stuidcard;
        this.school = school;
        this.edulevel = edulevel;
        this.major = major;
        this.edusystem = edusystem;
        this.edutype = edutype;
        this.edumode = edumode;
        this.branch = branch;
        this.classgrade = classgrade;
        this.stunum = stunum;
        this.admissiondate = admissiondate;
        this.leavedate = leavedate;
        this.stustate = stustate;
        this.remark = remark;
        this.isstuidentity = isstuidentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentroll
     *
     * @mbggenerated
     */
    public Studentroll() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.id
     *
     * @return the value of studentroll.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.id
     *
     * @param id the value for studentroll.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.stuname
     *
     * @return the value of studentroll.stuname
     *
     * @mbggenerated
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.stuname
     *
     * @param stuname the value for studentroll.stuname
     *
     * @mbggenerated
     */
    public void setStuname(String stuname) {
        this.stuname = stuname == null ? null : stuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.stusex
     *
     * @return the value of studentroll.stusex
     *
     * @mbggenerated
     */
    public String getStusex() {
        return stusex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.stusex
     *
     * @param stusex the value for studentroll.stusex
     *
     * @mbggenerated
     */
    public void setStusex(String stusex) {
        this.stusex = stusex == null ? null : stusex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.stuidcard
     *
     * @return the value of studentroll.stuidcard
     *
     * @mbggenerated
     */
    public String getStuidcard() {
        return stuidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.stuidcard
     *
     * @param stuidcard the value for studentroll.stuidcard
     *
     * @mbggenerated
     */
    public void setStuidcard(String stuidcard) {
        this.stuidcard = stuidcard == null ? null : stuidcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.school
     *
     * @return the value of studentroll.school
     *
     * @mbggenerated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.school
     *
     * @param school the value for studentroll.school
     *
     * @mbggenerated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.edulevel
     *
     * @return the value of studentroll.edulevel
     *
     * @mbggenerated
     */
    public String getEdulevel() {
        return edulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.edulevel
     *
     * @param edulevel the value for studentroll.edulevel
     *
     * @mbggenerated
     */
    public void setEdulevel(String edulevel) {
        this.edulevel = edulevel == null ? null : edulevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.major
     *
     * @return the value of studentroll.major
     *
     * @mbggenerated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.major
     *
     * @param major the value for studentroll.major
     *
     * @mbggenerated
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.edusystem
     *
     * @return the value of studentroll.edusystem
     *
     * @mbggenerated
     */
    public String getEdusystem() {
        return edusystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.edusystem
     *
     * @param edusystem the value for studentroll.edusystem
     *
     * @mbggenerated
     */
    public void setEdusystem(String edusystem) {
        this.edusystem = edusystem == null ? null : edusystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.edutype
     *
     * @return the value of studentroll.edutype
     *
     * @mbggenerated
     */
    public String getEdutype() {
        return edutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.edutype
     *
     * @param edutype the value for studentroll.edutype
     *
     * @mbggenerated
     */
    public void setEdutype(String edutype) {
        this.edutype = edutype == null ? null : edutype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.edumode
     *
     * @return the value of studentroll.edumode
     *
     * @mbggenerated
     */
    public String getEdumode() {
        return edumode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.edumode
     *
     * @param edumode the value for studentroll.edumode
     *
     * @mbggenerated
     */
    public void setEdumode(String edumode) {
        this.edumode = edumode == null ? null : edumode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.branch
     *
     * @return the value of studentroll.branch
     *
     * @mbggenerated
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.branch
     *
     * @param branch the value for studentroll.branch
     *
     * @mbggenerated
     */
    public void setBranch(String branch) {
        this.branch = branch == null ? null : branch.trim();
    }

    public String getClassgrade() {
        return classgrade;
    }

    public void setClassgrade(String classgrade) {
        this.classgrade = classgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.stunum
     *
     * @return the value of studentroll.stunum
     *
     * @mbggenerated
     */
    public String getStunum() {
        return stunum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.stunum
     *
     * @param stunum the value for studentroll.stunum
     *
     * @mbggenerated
     */
    public void setStunum(String stunum) {
        this.stunum = stunum == null ? null : stunum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.admissiondate
     *
     * @return the value of studentroll.admissiondate
     *
     * @mbggenerated
     */
    public Date getAdmissiondate() {
        return admissiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.admissiondate
     *
     * @param admissiondate the value for studentroll.admissiondate
     *
     * @mbggenerated
     */
    public void setAdmissiondate(Date admissiondate) {
        this.admissiondate = admissiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.leavedate
     *
     * @return the value of studentroll.leavedate
     *
     * @mbggenerated
     */
    public Date getLeavedate() {
        return leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.leavedate
     *
     * @param leavedate the value for studentroll.leavedate
     *
     * @mbggenerated
     */
    public void setLeavedate(Date leavedate) {
        this.leavedate = leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.stustate
     *
     * @return the value of studentroll.stustate
     *
     * @mbggenerated
     */
    public String getStustate() {
        return stustate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.stustate
     *
     * @param stustate the value for studentroll.stustate
     *
     * @mbggenerated
     */
    public void setStustate(String stustate) {
        this.stustate = stustate == null ? null : stustate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentroll.remark
     *
     * @return the value of studentroll.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentroll.remark
     *
     * @param remark the value for studentroll.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String getIsstuidentity() {
        return isstuidentity;
    }

    public void setIsstuidentity(String isstuidentity) {
        this.isstuidentity = isstuidentity;
    }
}